project_id = "vbbpwyekwpnbyygdxxlq"

[functions.send-invite]
verify_jwt = true

[functions.create-test-users]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.extract-part-from-drawing]
verify_jwt = false

[functions.npi-notify-change]
verify_jwt = false

[functions.parse-action-date]
verify_jwt = false
