(globalThis as any).localStorage = { getItem: () => null, setItem(){} };
import { buildInteractiveData, exportInteractiveCustomerReport } from './src/utils/npiInteractivePdf';
(globalThis as any).document = { createElement: () => ({ click(){}, set href(_:any){}, set download(_:any){} }) };
(globalThis as any).URL.createObjectURL = () => 'blob:x';
const rows:any[] = [];
const cust=['Alpha Corp','Beta Med','Gamma Ltd','Delta','Epsilon','Zeta','Eta','Theta','Iota','Kappa','Lambda'];
for (let m=0;m<12;m++) for (const c of cust) rows.push({customer:c,po:'P'+m,part:'X',revenue:Math.random()*50000,status:m%2?'O':'C',commodity:'',date:new Date(2026,m,5),isNpi:true});
const ds:any={site:'waterford',fileName:'f',rows,hasNpiCol:true,source:'database'};
const data=buildInteractiveData(ds,'Schivo Waterford','all',true);
console.log('months',data.months.length,'customers',data.customers.length);
await exportInteractiveCustomerReport(data);
console.log('OK');
import { writeFileSync } from 'fs';
writeFileSync('/tmp/out.pdf', Buffer.from((globalThis as any).__blobParts[0]));
console.log('wrote', (globalThis as any).__blobParts ? 'yes':'no');
